### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by jrochkind** [harvard-lil/stackview#19]
Hi, I'm trying to figure out the status of this project and it's relation to other projects. 

The last commit was about 9 months ago, which isn't too long ago. But I'm not sure what to make of the Issues reported that seem to have no reply, including one from 2013 suggesting incompatibilities with recent JQueries (#17). 

Is this software currently maintained? Also, is it currently in use in deployed software by the authors?

I originally got here from being impressed with the [StackLife demo](http://stacklife.harvard.edu/). Following the About -> GitHub links there, I get to the [StackLife github project](https://github.com/harvard-lil/stacklife) which appears to be an entire application stack. 

I'm instead interested in a Javascript front-end layer I can use with my own existing discovery layer. Which is how I arrive at this `stackview` repo, as that's what it appears to be. 

But what's the relationship between the full StackLife software, and this front-end stackview code? Does StackLife use `stackview` for it's front end code, use the very same software we find in this repo? Or is it a fork or copy-paste, two different versions?

In particular, the [StackLife demo](http://stacklife.harvard.edu/) seems to offer several features in it's virtual shelf browse that are not present in `stackview`. Notably the different graphical representations of different "formats".   Can I do this using the `stackview` code myself?  Customize it in the same way StackLife does, to get the same varying graphics for different formats?  Is the code StackLife uses to customize stackview, to do this, available open source as well, so I can use it for my own customizations?

Thanks for any orientation you can provide! I am very excited to potentially use stackview to provide a virtual shelf browse for our catalog here at Johns Hopkins Libraries.

**Comment by anniejocain** [comment]
Stack View is currently used in a slightly modified form by [StackLife](http://stacklife.harvard.edu/). Stack View is only the virtual stack representation. The rest of the StackLife front-end, things like searching, item records, bib info, is its own thing. StackLife uses a very slightly modified version of Stack View. Those modifications include changes to the call number sort option to fit with the API that powers StackLife.

Stack View does support five different formats. You can see those in the [types section of the source](https://github.com/harvard-lil/stackview/tree/master/src/js/types). Here is an [example JSON file](http://stacklife.harvard.edu/js/awesome.json?start=0&limit=25) that has different formats in it. This file feeds into the stack on the landing page of [StackLife](http://stacklife.harvard.edu/).

So yes you can use this version of Stack View to create virtual stacks in your application, complete with graphical representations of different formats. Let us know if you have any questions or run into any issues.

**Comment by jrochkind** [comment]
Awesome, thanks!  I did find the types by browsing the source code, sweet.

I also found the 'ministack' in the source code -- is that supposed to be optimization for small screens? Can you give me any info about that or how it's meant to be used? 

Are you open to pull requests? I might try to do some documentation pull requests to advertise the formats and the ministack (if I can figure out how it works). I am going to investigate #17, and if I reproduce it not working with more recent JQuery, I'll try to figure out how to fix and PR? 

I am also interested in my implementation being similar to the StackLife one where a click loads some info in a div on the page, rather than navigating to a new page. It seems like I might be able to do that simply with a javascript event handler (not sure how to do the effect where the selected book is nudged to the right), but if I end up needing any changes to source code to support that well, I would PR those too. 

Thanks for any advice. While I'm not an expert at javascript (I do more in ruby), looking at the source code, i am impressed by the clarity, conciseness, and general good design of your code, nice work.

**Comment by jrochkind** [comment]
oh, and I also think the demos don't work well on touch screens, you can not scroll the stack with touch-drag. I hope to figure out how to add support for that too, although I'm just beginning research on what that might entail. Your docs mention inclusion of special JS for mousewheel support, but I can't find that in the source, I think maybe the docs are out of date and no special mousewheel support JS was needed, it just works fine with standard browser scrolling support in current version?

**Comment by anniejocain** [comment]
Yes, apologies. The docs are out of date. The mousewheel JS requirement was dropped.


On 5/21/15 10:38 AM, "Jonathan Rochkind" <notifications@github.com> wrote:

oh, and I also think the demos don't work well on touch screens, you can not scroll the stack with touch-drag. I hope to figure out how to add support for that too, although I'm just beginning research on what that might entail. Your docs mention inclusion of special JS for mousewheel support, but I can't find that in the source, I think maybe the docs are out of date and no special mousewheel support JS was needed, it just works fine with standard browser scrolling support in current version?

**Comment by anniejocain** [comment]
We are definitely open to pull requests.

You can see the JS that StackLife uses to AJAX load on click starting at [line 254](https://github.com/harvard-lil/stacklife/blob/master/src/web/js/item.js#L254) or our item JS code. Click, call for some data, send the data to the page and then assign an active state to the selected item.

**Comment by jrochkind** [comment]
Thank you! That you can get the original data for the item from `data('stackviewItem')` is the key piece of info there, nice. 

Can you tell me anything about `loc_sort_order` in the source?  I was thinking I'd handle sorting entirely on the server-side and woudln't need any special client-side support, as long as I return items in the right sort order and support paging through them with `start` in the right sort order. 

But there's apparently some client side support for loc_sort_orders, that perhaps makes things easier, or takes care of something I'm not considering?  Can you tell me anything more about that? 

(And still curious about ministack, but I can probably figure it out playing with it)

**Comment by anniejocain** [comment]
Every item gets assigned one or more sort order numbers based on call number. This way items can appear in different places of the 'infinite stack' if they have multiple call numbers. 'loc_sort_order' also allows the stack to go both up and down. So when it initially loads there are items above and below the selected item and it will load more in either scroll direction. You can see more of how this is different from other stacks in the [source](https://github.com/harvard-lil/stackview/blob/master/src/js/jquery.stackview.base.js#L72).

We haven't used ministack much so I think tinkering with it is your best bet. Not sure if you saw the [test page](https://github.com/harvard-lil/stackview/blob/master/test/preview.html) but it has a ministack on it.

**Comment by jrochkind** [comment]
Thanks a lot for the tips @anniejocain. I filed a PR for fixing JQuery 1.9+ compat. 

I'm trying to figure out the loc_sort_order API/contract/expectations, by looking at the source and playing with it, because I am trying to do something similar, which the loc_sort_order feature may or may not be useful for my particular context. 

If you could give me a bit of context on how this expects the back-end system to operate, that would be helpful:

* It looks like the JS issues queries like `[x TO y]`, which looks kind of like a solr/lucene query; are you using solr/lucene on your back-end?
* It looks like it's expected that the results will include an `loc_sort_order` key with a whole number, that represents that call numbers absolute position in the ordering.  Is this right?
* If it is in Solr, what do you do in your Solr schema and indexing to create data for this? Do you actually have a 'document' in Solr for each call number (rather than for each book, which may have more than one call number), and actually assign the loc_sort_order whole number ranking somehow as part of indexing? 

Thanks if you can give me any tips.

**Comment by jrochkind** [comment]
Okay, I figured out how loc_sort_order works on the client end anyway. 

It would be convenient for me if the `start` parameter would be set even in `loc_sort_order` mode, in the request sent to the server script. 

For instance, when `query` = `[95 to 105]`, right now limit is still set to `10` as expected, but `start` is [set to 0](https://github.com/harvard-lil/stackview/blob/master/src/js/jquery.stackview.base.js#L88).

It would make things more straightforward for me if it were set to `95` to, matching the lower end. Would you accept a PR to that effect, will that cause any problems?

**Comment by anniejocain** [comment]
It might cause problems. We use a [translator in StackLife](https://github.com/harvard-lil/stacklife/blob/master/src/web/translators/cloud.php) to go between JS and Stack View so that we don't have to keep altering Stack View as our API changes. Would that approach work for you?

**Comment by jrochkind** [comment]
Sure, okay, I can handle it how it is, thanks. 

The Stackview api for the `loc_sort_order` is a bit weird, what it's really doing isn't specific to loc at all, it's just doing a 'window mode' where it can go backwards and forwards, and expresses the call to the server as a `query=[LOW TO HIGH]` instead of with `start` and `limit`.  Since both ways are capable of expressing the same thing, it's a bit confusing that the 'window' mode uses `query=[LOW TO HIGH]` vs start and limit, but I can handle it. 

I may be PR a enhancement where you can trigger this 'windowing' mode through something other than `search_type: loc_sort_order`, to make it less confusing exactly what it is. But if I do so, I will make it strictly backwards compat. 

I do have a couple bugfix PR's already, definitely appreciate you taking a look when you have time. 

I also plan to PR some documentation enhancements at some point, possibly after I try PR'ing some feature enhancements. 

Thanks! This is great to have this tool available, thanks for writing and releasing it.

**Comment by jrochkind** [comment]
Hi @anniejocain, Is your code for pulling page number and height out of MARC records available anywhere?  I know where those things are in the MARC record, but they're not entirely easily machine extractable, and it would be useful to see how you've done it.

**Comment by jrochkind** [comment]
Hi @anniejocain , thanks again for this code, I'm making great progress. 

Any chance you could review the PR's I've submitted over the past couple weeks? If you don't want to merge some of them, just let me know, and I'll see if I can figure out a way to apply them locally on top of stackview. 

I would definitely like to avoid having to make my own fork of stackview if I can avoid it. 

Also, is there any chance you could share the source of jquery.stackview.min.js as used in stacklife.harvard.edu, but un-minimized?  I can't find an un-minimized copy in the repo anywhere. I believe it has some changes and improvements to the version in this repo, and I'd like to be able to see them and compare.  In particular, stacklife.harvard.edu seems to does a better job of keeping the original center-point `id` near the top of the page on first load, compared to the code in this repo, and it's a tricky thing to do, it would be helpful to see how you've done it. 

Thank you for anything!

**Comment by anniejocain** [comment]
I'm afraid the source of StackLife's StackView is gone. I looked around everywhere for a copy but can't find it anywhere.

**Comment by jrochkind** [comment]
Okay, thanks Annie! Thanks for merging my PR's!

Maybe I'll try running stacklife's stackview through a de-minimizer, and see if that gives me something useful enough to get some ideas from.  It seems to be doing something to keep the 'origin' book near the top of the viewport on load, whereas with out of the box stacklife, it usually ends up toward the bottom end of the viewport, and sometimes off the screen entirely below viewport on a smaller laptop screen.  And I've been finding it a bit tricky to figure out how to do this reliably. 

I _think_ the code that's doing this is in the minimized stacklife, since I can't find it anywhere else in the (un-minimized) stacklife JS source.

**Comment by anniejocain** [comment]
Well, I feel like I vaguely remember that problem. In the haze of my mind I feel like it might have to do with items_per_page. I'll let you know if I think of anything else.

**Comment by jrochkind** [comment]
Cool. I've been exploring different approach of trying to figure out the right place to go to and using scrollTo to send the scrollable div there after load.  I can't figure out how items_per_page could work here, but I'll give it a bit of exploration with that hint. 

In the exploration I have been doing, I also noticed that there may be an "off by one" sort of error in the [scroll-fixing code in loc_search_mode prev_page](https://github.com/harvard-lil/stackview/blob/9a2d314dd0bd96f791df1eb21cfaa529de96e2c1/src/js/jquery.stackview.base.js#L400). The marker for where to return to ends up being the position of the _top_ of the the temporary placeholder,  which then gets removed, so isn't quite the right place to return to. 

I see this happening when I use a debugger to step through carefully, but it's odd that I don't seem to see it in actual live use, so maybe it's not an error. 

However, something I DO see in live use is occasionally, unpredictably, scrolling up to trigger a page load in loc_search_mode, even with a single press of the 'up' button sometimes end up doing a double load and leaving you confused where you are. I think this might be related, somehow.

**Comment by jrochkind** [comment]
PS: I don't want to share it publicly yet so don't want to put it on the ticket, but if you're interested in seeing my work in progress give me an email address and i'll send you an url. it's turning out pretty well.

**Comment by jrochkind** [comment]
Our local implementation is live:

https://catalyst.library.jhu.edu/shelfbrowse?origin_sort_key=HQ.1587.F4.2004---bib_2444395
